// <auto-generated />
using System;
using KitchenExcursion.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KitchenExcursion.Api.Migrations
{
    [DbContext(typeof(KitchenExcursionContext))]
    [Migration("20260920213943_AddRecipeRevisions")]
    partial class AddRecipeRevisions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("kitchen")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KitchenExcursion.Api.Models.Recipe", b =>
                {
                    b.Property<int>("RecipeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecipeId"));

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("CurrentRevisionId")
                        .HasColumnType("int");

                    b.Property<int>("HouseholdId")
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.HasKey("RecipeId");

                    b.HasIndex("CurrentRevisionId");

                    b.HasIndex("HouseholdId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Recipes", "kitchen");
                });

            modelBuilder.Entity("KitchenExcursion.Api.Models.RecipeCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("RecipeRevisionId")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RecipeRevisionId", "SortOrder")
                        .IsUnique();

                    b.ToTable("RecipeCategories", "kitchen");
                });

            modelBuilder.Entity("KitchenExcursion.Api.Models.RecipeCookLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTimeOffset>("CookedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RecipeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId", "CookedAt");

                    b.ToTable("RecipeCookLogs", "kitchen");
                });

            modelBuilder.Entity("KitchenExcursion.Api.Models.RecipeCookRating", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Rater")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<long>("RecipeCookLogId")
                        .HasColumnType("bigint");

                    b.Property<int>("Stars")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RecipeCookLogId", "Rater")
                        .IsUnique();

                    b.ToTable("RecipeCookRatings", "kitchen", t =>
                        {
                            t.HasCheckConstraint("CK_RecipeCookRatings_Stars", "[Stars] >= 1 AND [Stars] <= 5");
                        });
                });

            modelBuilder.Entity("KitchenExcursion.Api.Models.RecipeIngredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("RecipeRevisionId")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RecipeRevisionId", "SortOrder")
                        .IsUnique();

                    b.ToTable("RecipeIngredients", "kitchen");
                });

            modelBuilder.Entity("KitchenExcursion.Api.Models.RecipeRevision", b =>
                {
                    b.Property<int>("RecipeRevisionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecipeRevisionId"));

                    b.Property<string>("Badge")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("ChangeNote")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("CookTime")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("GeneralNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageAlt")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Meal")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Method")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("PrepTime")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Protein")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("RecipeId")
                        .HasColumnType("int");

                    b.Property<int>("RevisionNumber")
                        .HasColumnType("int");

                    b.Property<string>("Serves")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Summary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("nvarchar(240)");

                    b.HasKey("RecipeRevisionId");

                    b.HasIndex("RecipeId", "RevisionNumber")
                        .IsUnique();

                    b.ToTable("RecipeRevisions", "kitchen");
                });

            modelBuilder.Entity("KitchenExcursion.Api.Models.RecipeShoppingItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("RecipeRevisionId")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RecipeRevisionId", "SortOrder")
                        .IsUnique();

                    b.ToTable("RecipeShoppingItems", "kitchen");
                });

            modelBuilder.Entity("KitchenExcursion.Api.Models.RecipeStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("RecipeRevisionId")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id");

                    b.HasIndex("RecipeRevisionId", "SortOrder")
                        .IsUnique();

                    b.ToTable("RecipeStatuses", "kitchen");
                });

            modelBuilder.Entity("KitchenExcursion.Api.Models.RecipeStep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("RecipeRevisionId")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RecipeRevisionId", "SortOrder")
                        .IsUnique();

                    b.ToTable("RecipeSteps", "kitchen");
                });

            modelBuilder.Entity("KitchenExcursion.Api.Models.Recipe", b =>
                {
                    b.HasOne("KitchenExcursion.Api.Models.RecipeRevision", "CurrentRevision")
                        .WithMany()
                        .HasForeignKey("CurrentRevisionId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("CurrentRevision");
                });

            modelBuilder.Entity("KitchenExcursion.Api.Models.RecipeCategory", b =>
                {
                    b.HasOne("KitchenExcursion.Api.Models.RecipeRevision", "Revision")
                        .WithMany("Categories")
                        .HasForeignKey("RecipeRevisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Revision");
                });

            modelBuilder.Entity("KitchenExcursion.Api.Models.RecipeCookLog", b =>
                {
                    b.HasOne("KitchenExcursion.Api.Models.Recipe", "Recipe")
                        .WithMany("CookLogs")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("KitchenExcursion.Api.Models.RecipeCookRating", b =>
                {
                    b.HasOne("KitchenExcursion.Api.Models.RecipeCookLog", "CookLog")
                        .WithMany("Ratings")
                        .HasForeignKey("RecipeCookLogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CookLog");
                });

            modelBuilder.Entity("KitchenExcursion.Api.Models.RecipeIngredient", b =>
                {
                    b.HasOne("KitchenExcursion.Api.Models.RecipeRevision", "Revision")
                        .WithMany("Ingredients")
                        .HasForeignKey("RecipeRevisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Revision");
                });

            modelBuilder.Entity("KitchenExcursion.Api.Models.RecipeRevision", b =>
                {
                    b.HasOne("KitchenExcursion.Api.Models.Recipe", "Recipe")
                        .WithMany("Revisions")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("KitchenExcursion.Api.Models.RecipeShoppingItem", b =>
                {
                    b.HasOne("KitchenExcursion.Api.Models.RecipeRevision", "Revision")
                        .WithMany("ShoppingItems")
                        .HasForeignKey("RecipeRevisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Revision");
                });

            modelBuilder.Entity("KitchenExcursion.Api.Models.RecipeStatus", b =>
                {
                    b.HasOne("KitchenExcursion.Api.Models.RecipeRevision", "Revision")
                        .WithMany("Statuses")
                        .HasForeignKey("RecipeRevisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Revision");
                });

            modelBuilder.Entity("KitchenExcursion.Api.Models.RecipeStep", b =>
                {
                    b.HasOne("KitchenExcursion.Api.Models.RecipeRevision", "Revision")
                        .WithMany("Steps")
                        .HasForeignKey("RecipeRevisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Revision");
                });

            modelBuilder.Entity("KitchenExcursion.Api.Models.Recipe", b =>
                {
                    b.Navigation("CookLogs");

                    b.Navigation("Revisions");
                });

            modelBuilder.Entity("KitchenExcursion.Api.Models.RecipeCookLog", b =>
                {
                    b.Navigation("Ratings");
                });

            modelBuilder.Entity("KitchenExcursion.Api.Models.RecipeRevision", b =>
                {
                    b.Navigation("Categories");

                    b.Navigation("Ingredients");

                    b.Navigation("ShoppingItems");

                    b.Navigation("Statuses");

                    b.Navigation("Steps");
                });
#pragma warning restore 612, 618
        }
    }
}
